import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";

import Social from "@/app/components/social";

export const metadata: Metadata = {
  title: "Kino Newa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Social />
        {children}
      </body>
    </html>
  );
}
